name: Main workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable.yml
    with:
      dotnetVersions: '["6.x", "8.x"]'
