name: Main workflow

on: [push]

jobs:
  call-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get all .csproj files
        id: files
        run: |
          json="[]"

          # Busca todos os arquivos .csproj recursivamente
          for file in $(find . -name "*.csproj")
          do
              # Adiciona o caminho do arquivo ao JSON
              json=$(echo $json | jq --arg file "$file" '. + [$file]')
          done
          
          # Converte o JSON para string e imprime
          json_as_string=$(echo $json | jq -r tostring)
          echo $json_as_string
          echo "paths=$json_as_string" >> "$GITHUB_OUTPUT"

      - uses: ./.github/workflows/reusable.yml
        with:
          dotnetVersions: '["6.0.x", "8.0.x"]'
          projectPaths: '["./AllGenericThings/AllGenericThings.csproj","./MaxDegreeOfParallelism/dotnet-stuffs.csproj"]'
