name: Matrix from Input Example
on: 
  workflow_call:
    inputs:
      dotnetVersions:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ${{ github.event.inputs.dotnetVersions }}
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build
      run: dotnet build --configuration Release
