name: Matrix from Input Example
on: 
  workflow_call:
    inputs:
      dotnetVersions:
        required: true
        type: string
      projectPaths:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ${{ fromJSON(inputs.dotnetVersions) }}
        project: ${{ fromJSON(inputs.projectPaths) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet }}
      - name: Build
        if : ${{ matrix.project != '' }}
        run: dotnet build ${{ matrix.project }}
